Updated CI files

diff --git a/.github/workflows/ros_ttbcheck_ci.yml b/.github/workflows/ros_ttbcheck_ci.yml
--- a/.github/workflows/ros_ttbcheck_ci.yml
+++ b/.github/workflows/ros_ttbcheck_ci.yml
@@ -5,15 +5,21 @@ jobs:
     name: Run Timetable Checker
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v7
 
       - name: Setup Python for Parsing Output
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v6
         with:
-            python-version: '3.10'
+            python-version: '3.14'
 
       - name: Install RailOSTools
-        run: python -m pip install "git+https://github.com/Railway-Op-Sim/railostools.git@v0.5.5#egg=railostools&subdirectory=python"
+        run: python -m pip install "git+https://github.com/Railway-Op-Sim/railostools.git@v0.6.3#egg=railostools&subdirectory=python"
 
       - name: Validate Timetable
-        run: for ttb in $(find -name "*.ttb"); do railostools validate $ttb; done
+        run: |
+          set -e
+          find -iname "*.ttb" | while read ttb; do
+            echo "Validating $ttb"
+            railostools validate "$ttb" || (echo "Validation failed." && exit 1)
+            echo "Validation succeeded."
+          done
